# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-25 13:15
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.utils.utime


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('City', models.CharField(max_length=90, verbose_name='\u0413\u043e\u0440\u043e\u0434')),
                ('Sex', models.CharField(choices=[('', '\u041d\u0435 \u0432\u044b\u0431\u0440\u0430\u043d'), ('M', '\u041c\u0443\u0436'), ('F', '\u0416\u0435\u043d')], max_length=1, verbose_name='\u041f\u043e\u043b\u043e\u0432\u0438\u043d\u0430')),
                ('Age', models.DateField(null=True, verbose_name='\u0414\u0435\u043d\u044c \u0440\u043e\u0436\u0434\u0435\u043d\u0438\u044f')),
                ('Image', models.ImageField(upload_to='static/imagination', verbose_name='\u0412\u0430\u0448\u0435 \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': '\u0447\u0435\u043b\u043e\u0432\u0435\u043a\u0430',
                'verbose_name_plural': '\u041b\u044e\u0434\u0438',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Dialogue_Partakers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Last', models.IntegerField()),
                ('Dialogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talkers', to='main.Dialogue')),
                ('Profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DjangoInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approve', models.CharField(choices=[('0', '\u041d\u0435\u0438\u0437\u0432\u0435\u0441\u0442\u043d\u044b\u0439'), ('-1', '\u041d\u0435 \u043e\u0434\u043e\u0431\u0440\u0435\u043d\u043d\u044b\u0439'), ('1', '\u041e\u0434\u043e\u0431\u0440\u0435\u043d\u043d\u044b\u0439'), ('-0', '\u0418\u0441\u043a\u043b\u044e\u0447\u0435\u043d\u043d\u044b\u0439')], default='0', max_length=2)),
                ('date_initiative', models.DateTimeField(default=django.utils.timezone.now)),
                ('Quired_Relation', models.CharField(choices=[(1, '\u0414\u0440\u0443\u0433'), (2, '\u041b\u0438\u0447\u043d\u044b\u0439 \u0434\u0440\u0443\u0433'), (4, '\u0420\u043e\u0434\u0441\u0442\u0432\u0435\u043d\u043d\u0438\u043a')], default='1', max_length=12)),
                ('CurrentRelation', models.CharField(choices=[(1, '\u0414\u0440\u0443\u0433'), (2, '\u041b\u0438\u0447\u043d\u044b\u0439 \u0434\u0440\u0443\u0433'), (4, '\u0420\u043e\u0434\u0441\u0442\u0432\u0435\u043d\u043d\u0438\u043a')], default='0', max_length=12)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_friend', to=settings.AUTH_USER_MODEL)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_friend', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='INote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.TextField(verbose_name='\u0441\u043e\u0434\u0435\u0440\u0436\u0430\u043d\u0438\u0435')),
                ('Time', models.DateTimeField(auto_now=True, verbose_name='\u0412\u0440\u0435\u043c\u044f')),
            ],
            options={
                'ordering': ['Time'],
                'verbose_name': '\u0417\u0430\u043f\u0438\u0441\u044c',
                'verbose_name_plural': '\u0437\u0430\u043f\u0438\u0441\u0438',
            },
        ),
        migrations.CreateModel(
            name='Life',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.IntegerField()),
                ('Leaser', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='life', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value', models.CharField(max_length=50, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044e',
                'verbose_name_plural': '\u041c\u0435\u0442\u043a\u0430',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateTimeField(default=main.utils.utime.present_time)),
                ('Content', models.TextField()),
                ('Sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msgs', related_query_name='msgs', to=settings.AUTH_USER_MODEL)),
                ('Target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', related_query_name='messages', to='main.Dialogue')),
            ],
        ),
        migrations.CreateModel(
            name='Raiting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateTimeField(auto_now=True)),
                ('Value', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(-16), django.core.validators.MaxValueValidator(16)], verbose_name='\u041e\u0446\u0435\u043d\u043a\u0430')),
                ('From', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passed_Marks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['Time'],
                'verbose_name': '\u0440\u0435\u0439\u0442\u0438\u043d\u0433',
                'verbose_name_plural': '\u041e\u0442\u0434\u0430\u043d\u043d\u044b\u0439 \u0440\u0435\u0439\u0442\u0438\u043d\u0433',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('inote_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.INote')),
                ('Title', models.CharField(blank=True, max_length=100, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('Category', models.ManyToManyField(related_name='Articles', to='main.Mark', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f')),
            ],
            options={
                'verbose_name': '\u0417\u0430\u043c\u0435\u0442\u043a\u0430',
                'verbose_name_plural': '\u0437\u0430\u043c\u0435\u0442\u043a\u0430',
            },
            bases=('main.inote',),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('inote_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.INote')),
            ],
            options={
                'verbose_name': '\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439',
                'verbose_name_plural': '\u043a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439',
            },
            bases=('main.inote',),
        ),
        migrations.AddField(
            model_name='raiting',
            name='Target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gained_Marks', to='main.INote', verbose_name='\u0417\u0430\u043f\u0438\u0441\u044c'),
        ),
        migrations.AddField(
            model_name='inote',
            name='From',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dialogue',
            name='Partakers',
            field=models.ManyToManyField(related_name='dialogs', through='main.Dialogue_Partakers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='pals',
            field=models.ManyToManyField(through='main.Friends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AlterUniqueTogether(
            name='friends',
            unique_together=set([('by', 'friend')]),
        ),
        migrations.AddField(
            model_name='comment',
            name='Target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.INote', verbose_name='\u041a \u0447\u0435\u043c\u0443'),
        ),
    ]
