# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-25 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='life',
            name='d',
            field=models.BooleanField(default=True),
        ),
    ]
