# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-25 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_life_d'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='life',
            name='d',
        ),
        migrations.AlterField(
            model_name='life',
            name='Image',
            field=models.BinaryField(),
        ),
    ]
