# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-12-07 12:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191118_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='Author',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
