[tool.poetry]
name = "redis_connect"
version = "0.1.0"
description = ""
authors = ["DigmaBook <digital-mag@ya.ru>"]

[tool.poetry.dependencies]
python = "^2.7"
redis = "^3.4.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
